### ISSUE TITLE
Problem with the weather module.

### ISSUE THREAD

**Issue by jamesvcc** [aceinnolab/Inkycal#280] opened 2023-11-10 10:27 UTC
No matter where I put the weather module on the screen, it does not render the whole border correctly.  The top part of the border is missing.

![IMG_3195](https://github.com/aceinnolab/Inkycal/assets/61845576/d8dcc3b0-edfc-4176-8545-9ad8c8df8ddb)

I am using InkycalOS-Lite v2.0.3

Thanks,
James

**Comment by jamesvcc** [comment] 2023-11-10 10:29
Ah ha, worked out how to attach an image.

![IMG_3195](https://github.com/aceinnolab/Inkycal/assets/61845576/8b86835f-673c-48cd-9cba-39a697b62006)

**Comment by aceisace** [comment] 2023-11-10 11:29
Hi James, thanks for reporting this issue!
It's not clear yet whether or not this is a bug or just a configuration problem, but assuming it might be an issue with the paddings, you can try this:
```
sudo nano /boot/settings.json
# find the config section of the weather module,
# change these two values to 10:
"padding_x": 10,
"padding_y": 10,
```
Press `[CTRL]+[X]` at the same time, then `[Y]` to confirm. Lastly, reboot with `sudo reboot` and it should show the border. 

To help identifying what caused this issue, may I ask you to upload your settings.json file with any sensitive data removed? Then I can test the very same file locally to figure out why it happened in the first place 👍

**Comment by jamesvcc** [comment] 2023-11-10 12:25
Thank you – your suggestion worked.

The two values were set at:


"padding_x": 10,

"padding_y": 20,


I changed them as suggested and it now works.  Do you still want to see my settings.json file?

Best Regards,
James

From: Ace ***@***.***>
Date: Friday, 10 November 2023 at 11:29
To: aceinnolab/Inkycal ***@***.***>
Cc: jamesvcc ***@***.***>, Author ***@***.***>
Subject: Re: [aceinnolab/Inkycal] Problem with the weather module. (Issue #280)

Hi James, thanks for reporting this issue!
It's not clear yet whether or not this is a bug or just a configuration problem, but assuming it might be an issue with the paddings, you can try this:

sudo nano /boot/settings.json

# find the config section of the weather module,

# change these two values to 10:

"padding_x": 10,

"padding_y": 10,

Press [CTRL]+[X] at the same time, then [Y] to confirm. Lastly, reboot with sudo reboot and it should show the border.

To help identifying what caused this issue, may I ask you to upload your settings.json file with any sensitive data removed? Then I can test the very same file locally to figure out why it happened in the first place 👍

**Comment by aceisace** [comment] 2023-11-10 12:55
Glad to hear it worked 😄 
In this case, the issue is clearly with the paddings so no need to post the settings.json file  👍 
Closing this issue as the problem has been resolved

**Closed by aceisace** 2023-11-10 12:55 UTC
